default_language_version:
  python: python3.12
default_stages: [pre-commit]
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-json
      -   id: check-merge-conflict
      -   id: pretty-format-json
          args: ['--autofix']
      -   id: check-added-large-files
      -   id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
